<?php
if( function_exists('acf_add_local_field_group') ):

$ACF_foregrounds = array(
	'primary' => 'primary',
	'secondary' => 'secondary',
	'tertiary' => 'tertiary',
	'quaternary' => 'quaternary',
	'light' => 'light',
	'dark' => 'dark',
	'white' => 'white',
);

$ACF_backgrounds = array(
	'primary' => 'primary',
	'secondary' => 'secondary',
	'tertiary' => 'tertiary',
	'quaternary' => 'quaternary',
	'light' => 'light',
	'dark' => 'dark',
	'white' => 'white',
	'gradient-primary' => 'gradient-primary',
	'gradient-secondary' => 'gradient-secondary',
	'gradient-tertiary' => 'gradient-tertiary',
	'gradient-quaternary' => 'gradient-quaternary',
	'gradient-light' => 'gradient-light',
	'gradient-dark' => 'gradient-dark',
);

$ACF_heading_tags = array(
	'h1' => 'h1',
	'h2' => 'h2',
	'h3' => 'h3',
	'h4' => 'h4',
	'h5' => 'h5',
	'h6' => 'h6',
	'div' => 'div',
	'none' => 'none',
);

$ACF_heading_classes = array(
	'h1' => 'h1',
	'h2' => 'h2',
	'h3' => 'h3',
	'h4' => 'h4',
	'h5' => 'h5',
	'h6' => 'h6',
	'd-none' => 'd-none',
);

$ACF_containment = array(
	'container'       => 'Contained',
	'container-sm'    => 'Contained from S up';
	'container-md'    => 'Contained from M up';
	'container-lg'    => 'Contained from L up';
	'container-xl'    => 'Contained from XL up';
	'container-xl'    => 'Fluid';
	'wide'            => 'Full width',
);

acf_add_local_field_group(array(
	'name' => 'page_sections',
	'key' => 'group_5fce523299c83',
	'title' => 'Advanced Page Layout',
	'fields' => array(
		array(
			'key' => 'field_5fce52af3e9c5',
			'label' => 'Design Sections',
			'name' => 'design_sections',
			'type' => 'flexible_content',
			'instructions' => 'Sections of content to display instead of main page content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5fce52e5d6a98' => array(
					'key' => 'layout_5fce52e5d6a98',
					'name' => 'html_content',
					'label' => 'HTML Content',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce55e93e9cd',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce57843e9d0',
							'label' => 'Width',
							'name' => 'full_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'choices' => $ACF_containment,
							'default_value' => 'container',
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fce56c23e9cf',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_5fce58e73e9d4',
							'label' => 'Exact HTML',
							'name' => 'exact_html',
							'type' => 'true_false',
							'instructions' => 'If exact HTML, will avoid Wordpress paragraph munging.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Exact',
							'ui_off_text' => 'Munge',
						),
						array(
							'key' => 'field_5fce53ed3e9c8',
							'label' => 'Style',
							'name' => 'style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce541a3e9c9',
									'label' => 'Text colour',
									'name' => 'text_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_foregrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce54b83e9ca',
									'label' => 'Background colour',
									'name' => 'background_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_backgrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce54f33e9cb',
									'label' => 'Vertical padding',
									'name' => 'vertical_padding',
									'type' => 'number',
									'instructions' => 'A value from 0 (none) to 5 (most)',
									'required' => 0, 'allow_null' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 0,
									'max' => 5,
									'step' => 1,
								),
								array(
									'key' => 'field_5fce55c13e9cc',
									'label' => 'Additional classes',
									'name' => 'additional_classes',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce535e3e9c6',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce57b93e9d1',
							'label' => 'Heading Level',
							'name' => 'heading_level',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce535e3e9c6',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce57ef3e9d2',
									'label' => 'Real',
									'name' => 'real',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_tags,
									'default_value' => 'h2',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce58413e9d3',
									'label' => 'Visual',
									'name' => 'visual',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5fce57ef3e9d2',
												'operator' => '!=',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_classes,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce53b93e9c7',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fce5f171b108' => array(
					'key' => 'layout_5fce5f171b108',
					'name' => 'columns',
					'label' => 'Columns',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce5f171b109',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5f181b114',
							'label' => 'Width',
							'name' => 'full_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'choices' => $ACF_containment,
							'default_value' => 'container',
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fce5f181b115',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_5fce5f181b116',
							'label' => 'Exact HTML',
							'name' => 'exact_html',
							'type' => 'true_false',
							'instructions' => 'If exact HTML, will avoid Wordpress paragraph munging. Applies to both the "before columns" and "after columns" text.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Exact',
							'ui_off_text' => 'Munge',
						),
						array(
							'key' => 'field_5fce5f171b10a',
							'label' => 'Style',
							'name' => 'style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5f171b10b',
									'label' => 'Text colour',
									'name' => 'text_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_foregrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5f171b10c',
									'label' => 'Background colour',
									'name' => 'background_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_backgrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5f171b10d',
									'label' => 'Vertical padding',
									'name' => 'vertical_padding',
									'type' => 'number',
									'instructions' => 'A value from 0 (none) to 5 (most)',
									'required' => 0, 'allow_null' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 0,
									'max' => 5,
									'step' => 1,
								),
								array(
									'key' => 'field_5fce5f181b10e',
									'label' => 'Additional classes',
									'name' => 'additional_classes',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce5f181b10f',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5f181b110',
							'label' => 'Heading Level',
							'name' => 'heading_level',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce5f181b10f',
										'operator' => '!=empty',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5f181b111',
									'label' => 'Real',
									'name' => 'real',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_tags,
									'default_value' => 'h2',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5f181b112',
									'label' => 'Visual',
									'name' => 'visual',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5fce5f181b111',
												'operator' => '!=',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_classes,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_1fce5f181b110',
							'label' => 'Heading in Column',
							'name' => 'heading_in_column',
							'type' => 'true_false',
							'instructions' => 'Inserts the heading into the first column instead of before the columns.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce5f181b10f',
										'operator' => '!=empty',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Yes',
							'ui_off_text' => 'No',
						),
						array(
							'key' => 'field_5fce5f551b117',
							'label' => 'Before Columns',
							'name' => 'before_columns',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5fce5fc91b119',
							'label' => 'Columns',
							'name' => 'columns',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5fce601e1b11a',
							'min' => 1,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Column',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce601e1b11a',
									'label' => 'Content',
									'name' => 'content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '75',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_5fce61b66ec35',
									'label' => 'Options',
									'name' => 'options',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5fce61f56ec36',
											'label' => 'Classes',
											'name' => 'classes',
											'type' => 'text',
											'instructions' => 'Classes to apply to the column; requires knowledge of the Bootstrap grid system',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => 'col',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5fce62396ec37',
											'label' => 'Exact HTML',
											'name' => 'exact_html',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'ui' => 1,
											'ui_on_text' => 'Exact',
											'ui_off_text' => 'Munge',
										),
									),
								),
							),
						),
						array(
							'key' => 'field_5fce5fb11b118',
							'label' => 'After Columns',
							'name' => 'after_columns',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fce5b0ba0ea7' => array(
					'key' => 'layout_5fce5b0ba0ea7',
					'name' => 'primary_content',
					'label' => 'Primary Content',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce5b0ba0ea8',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'main',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5b0ba0eb3',
							'label' => 'Width',
							'name' => 'full_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'choices' => $ACF_containment,
							'default_value' => 'container',
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fce5b0ba0eb4',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_5fce5b0ba0ea9',
							'label' => 'Style',
							'name' => 'style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5b0ba0eaa',
									'label' => 'Text colour',
									'name' => 'text_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_foregrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5b0ba0eab',
									'label' => 'Background colour',
									'name' => 'background_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_backgrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5b0ba0eac',
									'label' => 'Vertical padding',
									'name' => 'vertical_padding',
									'type' => 'number',
									'instructions' => 'A value from 0 (none) to 5 (most)',
									'required' => 0, 'allow_null' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 0,
									'max' => 5,
									'step' => 1,
								),
								array(
									'key' => 'field_5fce5b0ba0ead',
									'label' => 'Additional classes',
									'name' => 'additional_classes',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce5b0ba0eae',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5b0ba0eaf',
							'label' => 'Heading Level',
							'name' => 'heading_level',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce5b0ba0eae',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5b0ba0eb0',
									'label' => 'Real',
									'name' => 'real',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_tags,
									'default_value' => 'h2',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5b0ba0eb1',
									'label' => 'Visual',
									'name' => 'visual',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5fce5b0ba0eb0',
												'operator' => '!=',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_classes,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fce5ceba0ec6' => array(
					'key' => 'layout_5fce5ceba0ec6',
					'name' => 'foogallery',
					'label' => 'FooGallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce5ceba0ec7',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5ceba0ed1',
							'label' => 'Width',
							'name' => 'full_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'choices' => $ACF_containment,
							'default_value' => 'container',
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fce5ceba0ed2',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_5fce5d03a0ed4',
							'label' => 'Gallery Id',
							'name' => 'gallery_id',
							'type' => 'number',
							'instructions' => 'Numeric identifier for gallery, found in FooGallery as part of the shortcode.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5fce5ceba0ec8',
							'label' => 'Style',
							'name' => 'style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5ceba0ec9',
									'label' => 'Text colour',
									'name' => 'text_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_foregrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5ceba0eca',
									'label' => 'Background colour',
									'name' => 'background_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_backgrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5ceba0ecb',
									'label' => 'Vertical padding',
									'name' => 'vertical_padding',
									'type' => 'number',
									'instructions' => 'A value from 0 (none) to 5 (most)',
									'required' => 0, 'allow_null' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 0,
									'max' => 5,
									'step' => 1,
								),
								array(
									'key' => 'field_5fce5ceba0ecc',
									'label' => 'Additional classes',
									'name' => 'additional_classes',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce5ceba0ecd',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5ceba0ece',
							'label' => 'Heading Level',
							'name' => 'heading_level',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce5ceba0ecd',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce5ceba0ecf',
									'label' => 'Real',
									'name' => 'real',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_tags,
									'default_value' => 'h2',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce5ceba0ed0',
									'label' => 'Visual',
									'name' => 'visual',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5fce5ceba0ecf',
												'operator' => '!=',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_classes,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fce6787af28f' => array(
					'key' => 'layout_5fce6787af28f',
					'name' => 'post',
					'label' => 'Post',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce6787af290',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce6787af29b',
							'label' => 'Width',
							'name' => 'full_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'choices' => $ACF_containment,
							'default_value' => 'container',
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fce6787af29c',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_5fce6787af291',
							'label' => 'Post',
							'name' => 'post_id',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'post_type' => '',
							'taxonomy' => '',
							'allow_null' => 1,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
						array(
							'key' => 'field_5fce6787af292',
							'label' => 'Style',
							'name' => 'style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce6787af293',
									'label' => 'Text colour',
									'name' => 'text_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_foregrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce6787af294',
									'label' => 'Background colour',
									'name' => 'background_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_backgrounds,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce6787af295',
									'label' => 'Vertical padding',
									'name' => 'vertical_padding',
									'type' => 'number',
									'instructions' => 'A value from 0 (none) to 5 (most)',
									'required' => 0, 'allow_null' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 0,
									'max' => 5,
									'step' => 1,
								),
								array(
									'key' => 'field_5fce6787af296',
									'label' => 'Additional classes',
									'name' => 'additional_classes',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_5fce6787af297',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce6787af298',
							'label' => 'Heading Level',
							'name' => 'heading_level',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fce6787af297',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5fce6787af299',
									'label' => 'Real',
									'name' => 'real',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_tags,
									'default_value' => 'h2',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5fce6787af29a',
									'label' => 'Visual',
									'name' => 'visual',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5fce6787af299',
												'operator' => '!=',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => $ACF_heading_classes,
									'default_value' => false,
									'allow_null' => 1,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fce5d50a0ed5' => array(
					'key' => 'layout_5fce5d50a0ed5',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fce5d50a0ed6',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting (section tag)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5d50a0ee2',
							'label' => 'Hidden',
							'name' => 'hidden',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Hidden',
							'ui_off_text' => 'Shown',
						),
						array(
							'key' => 'field_666e5d50a7ed6',
							'label' => 'Image ID',
							'name' => 'img_id',
							'type' => 'text',
							'instructions' => 'HTML `id` attribute for styling and scripting (img tag)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_666e5d50a0ed6',
							'label' => 'Image Classes',
							'name' => 'img_class',
							'type' => 'text',
							'instructions' => 'HTML `class` attribute for styling and scripting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'w-100 h-auto',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fce5d7ea0ee3',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => 0,
			'max' => 50,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
